### ISSUE TITLE
Use with ARKit3

### ISSUE THREAD

**Issue by vegiwoo** [palle-k/GVRSCNRenderer#1]
I am trying to associate `ARSCNView` with rendering of` GVRSCNARTrackingRenderer` and when I try to specify `let renderer = GVRSCNARTrackingRenderer (scene: arView.scene)`, I get no result. In addition, when you press the Cardboard button on the screen, even when you try to add a normal SCNScene, screen separation does not occur. Tell me how to correctly implement the presentation functionality with a split screen for two eyes, while showing ARSCNView?

**Comment by palle-k** [comment]
You have to use `GVRRendererView` (which is part of `GVRKit`) instead of `ARSCNView`.
